:source ~/.vim/conf/autocmd.vim
:source ~/.vim/conf/codestyle.vim
:source ~/.vim/conf/cpplight.vim
:source ~/.vim/conf/devicons.vim
:source ~/.vim/conf/funcs.vim
:source ~/.vim/conf/keymap.vim
:source ~/.vim/conf/LeaderF.vim
:source ~/.vim/conf/markdown.vim
:source ~/.vim/conf/other.vim
:source ~/.vim/conf/rainbow.vim
:source ~/.vim/conf/coc.vim
:source ~/.vim/conf/nerdtree.vim
